language: go

go:
    - 1.13
env:
    global:
        - GO111MODULE=on
        - secure: "Cf4QuSKgrQBulMQV0a6ID+rhX2y6UKuZmpq0renPGEMer2FNzVVOe0cQCxyMrBMU6w3bpYMaxo9//38qBzf0Z6Eht0ocS8sNUJCRcA0VdzyqWqK1ftChaVM3804sl/Z7V5ij53IKa7H//7tLQTGQV7XQRsWPvkHVex44wohP898yB+Pjpo56QwbjI9NUfw7NRP22bi52q+jsA8JP+QeYi7chy3LXPBHmCf4ZWCoNh9d7Lo+WDP5U6Mfe2/4vvUPVcJ8huJF7cAmy9r05+DQcKLKpBJjNxI9LBZlTSOlVArLj974iLfRXjqR182UHYMTGhqCGejiCimGNEiCuoOzVgk9JUfm/ssxXjGzv6uZATZsRyCf4SgopTsikEv4SCH/fpfpE7lTARDURaKMl0VRivR10mm92vysfi/hF0/y9FQqeEAxLhMlsPC1Xa0ppGqX+Ne57Aq9aj2Rxa9EU+ik6GqP281RwS6IxnqPUIX7XAnKY6EcYGB2egMuNadISNyomsbZfGEIZ5whogXxxADaC/L/3uT6kW1EJ8gJ6kCwagLc3sI8wcekH/K6exBmC18fDE4sI2DDTBqDfDKv5sE9dWwUcdgKv/PzsJZLOv5QXkpvwyS3aI/zh26PCQp3SGxeN5QZ3tKDAPjiAjNVMeWt7+O4Dp5brVyXmUyuJOwcHVVM="

before_script:
    - go get github.com/mattn/goveralls

script:
    - make test build
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
